### PR TITLE
Improve physics, fix DPI issue

### PR DESCRIPTION
**Pull request by jarhill0**
This PR adds support for colliding with the ground to the game engine and the GUI. It also fixes a graphical issue in the GUI that has to do with changing DPI.

### CODE REVIEW

**Comment by jarhill0** [comment]
> You're passing 0 just until you implement the scoring mechanism. At this point, when you detect the game is over, you will calculate the score, set gameFinished=true; and then pass makeState(score).

Bingo! Right on. I haven't gotten around to calculating score, and I wanna discuss score calculation with you guys.

**Comment by wknowleskellett** [comment]
Do you mind if I do a small score method, and then we can pull it and make a better one later?

Also, if I do that, how can I tell when the person has landed?

**Comment by jarhill0** [comment]
Yeah sure! You can merge this and then create a new branch for your score method. 

The ship has landed when its height is <= 0, which is equivalent to when the game over flag is true.

**Comment by wknowleskellett** [comment]
"score" is already in GameEngine.h as a class variable, could I just use that instead of passing it to makeState()? I think that may be easier, since another method will calculate score.

**Comment by jarhill0** [comment]
`score` is not a member of the [`GameEngine`](https://github.com/jarhill0/MoonLander/blob/61458896b653b7f1d20b73b14878e4d9836b89fc/src/GameEngine.h#L34-L53) class. It is a member of the struct [`GameState`](https://github.com/jarhill0/MoonLander/blob/61458896b653b7f1d20b73b14878e4d9836b89fc/src/GameEngine.h#L25). There's no "using that" — that is the result that must be made.

I think the score should either be a parameter of `makeState()` (i.e. `makeState(calcScore())`), or `makeState()` should call out to a method that calculates it.

**Comment by wknowleskellett** [comment]
I'm going to dinner - can you check out my branch? It's not gonna compile, but maybe you'll see what I'm going for with the changes I've made.
I think it makes sense to calculate the score a single time right when the game ends, and afterwards have it be an attribute of that GameEngine

**Comment by jarhill0** [comment]
I'm not quite sure I understand your score function, but I'll play around with it.

I don't think you should be removing `gameFinished = true` as you do in your commit, but that's minor.

Let's discuss in person when we get the chance!

**Comment by wknowleskellett** [comment]
I added gameFinished=true to the score function, so that the function just represents the end of game; I definitely agree it shouldn't be removed. Until I set up my Windows more fully, I won't be able to compile, and see what errors I'm getting, so I'm kinda riding blind in terms of those errors. I'll try to set it up and get back to it.

**Pull request merged**
