### PR TITLE
Input State and Rewrites

### PR DESCRIPTION
**Pull request by 18goldr**
I think an input state should be represented by some sort of structure like a string. It makes sense because any combination of keys can be pressed at the same time and it fits with how I envision the GP would represent the data (see gp.txt).

Aside from that, all I did was rewrite things.

### CODE REVIEW

**Comment by jarhill0** [comment]
Thanks for this!

Strings are not the right choice for input state. We have three inputs (up, left, right) which can be either pressed or not pressed. This is analogous to three booleans, or three booleans in a struct, as William's document suggests. 

Other than that I like the updates you've made. Thanks!

**Comment by jarhill0** [comment]
Also, gp.txt looks super cool. I don't know much about the ML stuff but I'm glad that you're planning it out.

**Comment by jarhill0** [comment]
See #2, where I've stubbed the game engine.

**Comment by 18goldr** [comment]
Yes, but the point is that these inputs can all be pressed at the same time. Therefore, if we were to use booleans it would have be a struct/class, which would make it more complicated the parse the series of actions an individual performed. If it is implemented as string, parsing the actions would be easy as simply checking each character, rather than having to check each field of the class/struct individually.

**Comment by jarhill0** [comment]
Thanks for the response.

I think you're misunderstanding either the game engine or the ML plans or both. 

From the perspective of the game, a frame is rendered, input is polled, the world steps forward, a frame is rendered, etc. At each time that input is polled, each of the three inputs is either activated or not. Adding string (or string-like) processing adds complexity. Internally, the engine will want to translate string(like)s to boolean values, because engine code will really be asking "is this key pressed or not?". With your siggestion, the engine would have to parse and validate a string of unspecified length rather than a well-defined four-byte structure. 

On the ML side, there will be some function/NN/idk that takes some number of inputs (around 10) and processes that, yielding three outputs corresponding to the three inputs. I don't see how encoding three values (likely doubles between 0 and 1, from my understanding) to strings simplifies the process. 

It really comes down to a modeling issue. What (somewhat abstract) computer concept corresponds best to a real-world concept? These types of questions can have multiple answers because the real world is messy and doesn't map cleanly onto the rigid computer world. I think you'd agree that using three booleans is *a* reasonable solution, even if you don't see it as *the* best solution. 

I'm closing this now because the game engine has been stubbed and merged. That's not to say it can't or won't change, but I think we've discussed it enough.

**Comment by jarhill0** [comment]
By the way, I don't understand why you say frames are irrelevant for the ML program. I addressed it in my previous comment, but the ML program will be operating on input per-frame just like a human would. If each "ML" program is really just a sequence of actions that disregards all input, we're just trying to find the "best constant path," which is gonna be much easier to calculate by hand.

**Pull request closed without merging**
