### PR TITLE
Stub GameEngine methods

### PR DESCRIPTION
**Pull request by jarhill0**
I've stubbed GameEngine methods. The GameEngine class will have two methods: a constructor and a step.

In GameEngine.h I define input and output values:

1. GameState (output)
    - float fuel
    - float shipYPos
    - float shipXPos
    - float shipYVelocity
    - float shipXVelocity
    - float shipRotation
    - float shipAngularVelocity
    - boolean gameOver
    - int score

2. InputState (input)
    - boolean mainThruster
    - boolean rotLeftThruster
    - boolean rotRightThruster

3. class GameEngine 
    - constructor
    - GameState step(InputState)
    - int score()

4. int score()
    returns the score output of the game (int)

I *believe* I have covered all of the necessary inputs and outputs. If there's something you think you need, let me know.

I'm (think I'm) using C++ paradigms correctly — things like `std::cout` (to replace `puts` and `printf`) and `new` and `delete` (to replace `malloc` and `free`).

### CODE REVIEW

**Comment by wknowleskellett** [comment]
Can somebody who understands c++ check his syntax before we merge?
I would learn and check it tonight, but I haven't gotten a chance to finish my report.

**Comment by jarhill0** [comment]
Syntax should be good. It compiles and runs. 

If you think it conforms to your design, I encourage merging it!

**Comment by wknowleskellett** [comment]
few tweaks - one sec

**Comment by wknowleskellett** [comment]
So, what I did was change the score variable to now come out of a separate function, which ML/GUI knows to call when GameState.gameOver == true
I then added an appropriate method to GameEngine.
I also changed the constructor to be an init() function so that it can be reset time and time again. This last change is negotiable, as we could just construct a new game engine the way Joey had it. My edit works better with all of GameEngine working offa static stuff.
Thoughts?

**Comment by jarhill0** [comment]
I don't see the changes that you claim to have made. 

As for score, it doesn't matter much either way, but I did it this way to avoid some complexity. I don't think we need a separate function call to retrieve data that can be returned in a function we're already calling. Also, what happens if the score method is erroneously called before the end of the game? That would introduce some exception throwing/handling that we don't really need. 

As for constructor versus init, C++ is an object-oriented language (like Java), and so we should be using objects and constructors. To me, "init" sounds like the name of a constructor (in Python, `__init___` is the constructor).

Maybe as a compromise we could add a `clear` method? I'm not sure I understand the use-case for "re-using" an object for multiple instances. 

Can you explain what you mean by "static" in this context?

Thanks for the awesome feedback.

**Comment by wknowleskellett** [comment]
My reason for moving score was something we talked about at lunch, where when I brought up having score be returned in GameState we came to the conclusion it should be a separate function called later.
By "static," I meant that the GameEngine would have no concept of multiple instances of itself, but would be running a single game, with static variables, which would happily set itself to start when init() was called. While __init__() _is_ a python method, I just meant it in the generic sense of initialization. It initializes the game with the ship at 0 velocity (or something else predetermined) and the correct position above the landing pad every time it is called.

**Comment by wknowleskellett** [comment]
*I'm happy doing instances of GameEngine and non-static variables

**Comment by jarhill0** [comment]
I can certainly add a method for getting score at the end if you want. I also don't see a reason to remove it from GameState (both can coexist).

What I remember discussing at lunch was providing a nonzero score even for crash landings. 

As for what you're saying about making GameEngine static, I don't see any benefit. The harms that I see are that (a) by using static (global) state, we would not ever be able to run more than one game at once, which would prevent parallelizing training, and (b) it goes against the object-oriented paradigms of C++. If you feel strongly, can we call if you're free some time this weekend? I know you're quite busy this weekend so no worries if you can't.

**Comment by wknowleskellett** [comment]
Forget static - idea happily withdrawn; it doesn't make sense.

I also don't feel strongly about score, but it may help with scope in the ML to be able to access it outside of the loop where we call step().
Having it both places works great.

**Comment by wknowleskellett** [comment]
Sweet, merging

**Pull request merged**
